File didn't exist so we created it by catching exceptions
